# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-08 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0002_auto_20190708_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_description',
            new_name='description',
        ),
    ]
